version: '1'
services:
  laravel-docker:
    build: ./
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/cadastrousuariolaravel/
    restart: always
    networks:
      - docker

networks:
  docker:
    driver: bridge
